name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./front-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front-end:latest
          platform: linux/amd64    
          
  deploy:
    runs-on: ubuntu-latest
    needs: dockerhub-push
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: monkfish-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}



